set(_CATKIN_CURRENT_PACKAGE "test_bond")
set(test_bond_VERSION "1.8.4")
set(test_bond_MAINTAINER "Michael Carroll <michael@openrobotics.org>")
set(test_bond_PACKAGE_FORMAT "2")
set(test_bond_BUILD_DEPENDS "bondcpp" "cmake_modules" "message_generation" "rostest")
set(test_bond_BUILD_EXPORT_DEPENDS )
set(test_bond_BUILDTOOL_DEPENDS "catkin")
set(test_bond_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(test_bond_BUILDTOOL_EXPORT_DEPENDS )
set(test_bond_EXEC_DEPENDS )
set(test_bond_RUN_DEPENDS )
set(test_bond_TEST_DEPENDS "bondpy" "uuid")
set(test_bond_DOC_DEPENDS )
set(test_bond_URL_WEBSITE "http://www.ros.org/wiki/test_bond")
set(test_bond_URL_BUGTRACKER "https://github.com/ros/bond_core/issues")
set(test_bond_URL_REPOSITORY "https://github.com/ros/bond_core")
set(test_bond_DEPRECATED "")