
(cl:in-package :asdf)

(defsystem "kdl_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :std_msgs-msg
)
  :components ((:file "_package")
    (:file "Chain" :depends-on ("_package_Chain"))
    (:file "_package_Chain" :depends-on ("_package"))
    (:file "Frame" :depends-on ("_package_Frame"))
    (:file "_package_Frame" :depends-on ("_package"))
    (:file "FrameStamped" :depends-on ("_package_FrameStamped"))
    (:file "_package_FrameStamped" :depends-on ("_package"))
    (:file "Jacobian" :depends-on ("_package_Jacobian"))
    (:file "_package_Jacobian" :depends-on ("_package"))
    (:file "JntArray" :depends-on ("_package_JntArray"))
    (:file "_package_JntArray" :depends-on ("_package"))
    (:file "JntArrayStamped" :depends-on ("_package_JntArrayStamped"))
    (:file "_package_JntArrayStamped" :depends-on ("_package"))
    (:file "Joint" :depends-on ("_package_Joint"))
    (:file "_package_Joint" :depends-on ("_package"))
    (:file "RigidBodyInertia" :depends-on ("_package_RigidBodyInertia"))
    (:file "_package_RigidBodyInertia" :depends-on ("_package"))
    (:file "Rotation" :depends-on ("_package_Rotation"))
    (:file "_package_Rotation" :depends-on ("_package"))
    (:file "RotationStamped" :depends-on ("_package_RotationStamped"))
    (:file "_package_RotationStamped" :depends-on ("_package"))
    (:file "RotationalInertia" :depends-on ("_package_RotationalInertia"))
    (:file "_package_RotationalInertia" :depends-on ("_package"))
    (:file "Segment" :depends-on ("_package_Segment"))
    (:file "_package_Segment" :depends-on ("_package"))
    (:file "Twist" :depends-on ("_package_Twist"))
    (:file "_package_Twist" :depends-on ("_package"))
    (:file "TwistStamped" :depends-on ("_package_TwistStamped"))
    (:file "_package_TwistStamped" :depends-on ("_package"))
    (:file "Vector" :depends-on ("_package_Vector"))
    (:file "_package_Vector" :depends-on ("_package"))
    (:file "VectorStamped" :depends-on ("_package_VectorStamped"))
    (:file "_package_VectorStamped" :depends-on ("_package"))
    (:file "Wrench" :depends-on ("_package_Wrench"))
    (:file "_package_Wrench" :depends-on ("_package"))
    (:file "WrenchStamped" :depends-on ("_package_WrenchStamped"))
    (:file "_package_WrenchStamped" :depends-on ("_package"))
  ))