# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/msg/ContactsState.msg;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/msg/ContactState.msg;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/msg/LinkState.msg;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/msg/LinkStates.msg;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/msg/ModelState.msg;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/msg/ModelStates.msg;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/msg/ODEJointProperties.msg;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/msg/ODEPhysics.msg;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/msg/WorldState.msg"
services_str = "/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/ApplyBodyWrench.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/DeleteModel.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/DeleteLight.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/GetLinkState.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/GetPhysicsProperties.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/SetJointProperties.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/SetModelConfiguration.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/SpawnModel.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/ApplyJointEffort.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/GetJointProperties.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/GetModelProperties.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/GetWorldProperties.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/SetLinkProperties.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/SetModelState.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/BodyRequest.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/GetLinkProperties.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/GetModelState.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/JointRequest.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/SetLinkState.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/SetPhysicsProperties.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/SetJointTrajectory.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/GetLightProperties.srv;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/srv/SetLightProperties.srv"
pkg_name = "gazebo_msgs"
dependencies_str = "std_msgs;geometry_msgs;sensor_msgs;trajectory_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "gazebo_msgs;/home/pi/test/src/gazebo_ros_pkgs/gazebo_msgs/msg;std_msgs;/home/pi/test/src/std_msgs/msg;geometry_msgs;/home/pi/test/src/common_msgs/geometry_msgs/msg;sensor_msgs;/home/pi/test/src/common_msgs/sensor_msgs/msg;trajectory_msgs;/home/pi/test/src/common_msgs/trajectory_msgs/msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/home/pi/ros_catkin_ws/build/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
