set(_CATKIN_CURRENT_PACKAGE "test_nodelet")
set(test_nodelet_VERSION "1.9.16")
set(test_nodelet_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(test_nodelet_PACKAGE_FORMAT "2")
set(test_nodelet_BUILD_DEPENDS "nodelet" "pluginlib" "rostest" "std_msgs")
set(test_nodelet_BUILD_EXPORT_DEPENDS "nodelet" "pluginlib" "rostest" "std_msgs")
set(test_nodelet_BUILDTOOL_DEPENDS "catkin")
set(test_nodelet_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(test_nodelet_BUILDTOOL_EXPORT_DEPENDS )
set(test_nodelet_EXEC_DEPENDS "nodelet" "pluginlib" "rostest" "std_msgs")
set(test_nodelet_RUN_DEPENDS "nodelet" "pluginlib" "rostest" "std_msgs")
set(test_nodelet_TEST_DEPENDS "rosbash")
set(test_nodelet_DOC_DEPENDS )
set(test_nodelet_URL_WEBSITE "http://ros.org/wiki/test_nodelet")
set(test_nodelet_URL_BUGTRACKER "https://github.com/ros/nodelet_core/issues")
set(test_nodelet_URL_REPOSITORY "https://github.com/ros/nodelet_core")
set(test_nodelet_DEPRECATED "")