set(_CATKIN_CURRENT_PACKAGE "test_nodelet_topic_tools")
set(test_nodelet_topic_tools_VERSION "1.9.16")
set(test_nodelet_topic_tools_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(test_nodelet_topic_tools_PACKAGE_FORMAT "2")
set(test_nodelet_topic_tools_BUILD_DEPENDS "rostest" "message_filters" "nodelet" "nodelet_topic_tools" "pluginlib" "roscpp" "std_msgs")
set(test_nodelet_topic_tools_BUILD_EXPORT_DEPENDS "message_filters" "nodelet" "nodelet_topic_tools" "pluginlib" "roscpp" "std_msgs")
set(test_nodelet_topic_tools_BUILDTOOL_DEPENDS "catkin")
set(test_nodelet_topic_tools_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(test_nodelet_topic_tools_BUILDTOOL_EXPORT_DEPENDS )
set(test_nodelet_topic_tools_EXEC_DEPENDS "message_filters" "nodelet" "nodelet_topic_tools" "pluginlib" "roscpp" "std_msgs")
set(test_nodelet_topic_tools_RUN_DEPENDS "message_filters" "nodelet" "nodelet_topic_tools" "pluginlib" "roscpp" "std_msgs")
set(test_nodelet_topic_tools_TEST_DEPENDS "rospy")
set(test_nodelet_topic_tools_DOC_DEPENDS )
set(test_nodelet_topic_tools_URL_WEBSITE "http://ros.org/wiki/nodelet_topic_tools")
set(test_nodelet_topic_tools_URL_BUGTRACKER "https://github.com/ros/nodelet_core/issues")
set(test_nodelet_topic_tools_URL_REPOSITORY "https://github.com/ros/nodelet_core")
set(test_nodelet_topic_tools_DEPRECATED "")