set(_CATKIN_CURRENT_PACKAGE "nodelet")
set(nodelet_VERSION "1.9.16")
set(nodelet_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(nodelet_PACKAGE_FORMAT "2")
set(nodelet_BUILD_DEPENDS "cmake_modules" "message_generation" "bondcpp" "boost" "pluginlib" "rosconsole" "roscpp" "std_msgs" "uuid")
set(nodelet_BUILD_DEPENDS_cmake_modules_VERSION_GTE "0.3.2")
set(nodelet_BUILD_DEPENDS_pluginlib_VERSION_GTE "1.10.0")
set(nodelet_BUILD_EXPORT_DEPENDS "bondcpp" "boost" "pluginlib" "rosconsole" "roscpp" "std_msgs" "uuid")
set(nodelet_BUILD_EXPORT_DEPENDS_pluginlib_VERSION_GTE "1.10.0")
set(nodelet_BUILDTOOL_DEPENDS "catkin")
set(nodelet_BUILDTOOL_EXPORT_DEPENDS )
set(nodelet_EXEC_DEPENDS "message_runtime" "rospy" "bondcpp" "boost" "pluginlib" "rosconsole" "roscpp" "std_msgs" "uuid")
set(nodelet_EXEC_DEPENDS_pluginlib_VERSION_GTE "1.10.0")
set(nodelet_RUN_DEPENDS "message_runtime" "rospy" "bondcpp" "boost" "pluginlib" "rosconsole" "roscpp" "std_msgs" "uuid")
set(nodelet_RUN_DEPENDS_pluginlib_VERSION_GTE "1.10.0")
set(nodelet_TEST_DEPENDS )
set(nodelet_DOC_DEPENDS )
set(nodelet_URL_WEBSITE "http://ros.org/wiki/nodelet")
set(nodelet_URL_BUGTRACKER "https://github.com/ros/nodelet_core/issues")
set(nodelet_URL_REPOSITORY "https://github.com/ros/nodelet_core")
set(nodelet_DEPRECATED "")