set(_CATKIN_CURRENT_PACKAGE "test_diagnostic_aggregator")
set(test_diagnostic_aggregator_VERSION "1.9.3")
set(test_diagnostic_aggregator_MAINTAINER "Brice Rebsamen <brice.rebsamen@gmail.com>, Austin Hendrix <namniart@gmail.com>")
set(test_diagnostic_aggregator_PACKAGE_FORMAT "1")
set(test_diagnostic_aggregator_BUILD_DEPENDS "diagnostic_aggregator" "diagnostic_msgs" "pluginlib" "roscpp" "rospy" "rostest")
set(test_diagnostic_aggregator_BUILD_DEPENDS_diagnostic_aggregator_VERSION_GTE "1.8.9")
set(test_diagnostic_aggregator_BUILD_EXPORT_DEPENDS "diagnostic_aggregator" "diagnostic_msgs" "pluginlib" "roscpp" "rospy")
set(test_diagnostic_aggregator_BUILD_EXPORT_DEPENDS_diagnostic_aggregator_VERSION_GTE "1.8.9")
set(test_diagnostic_aggregator_BUILDTOOL_DEPENDS "catkin")
set(test_diagnostic_aggregator_BUILDTOOL_EXPORT_DEPENDS )
set(test_diagnostic_aggregator_EXEC_DEPENDS "diagnostic_aggregator" "diagnostic_msgs" "pluginlib" "roscpp" "rospy")
set(test_diagnostic_aggregator_EXEC_DEPENDS_diagnostic_aggregator_VERSION_GTE "1.8.9")
set(test_diagnostic_aggregator_RUN_DEPENDS "diagnostic_aggregator" "diagnostic_msgs" "pluginlib" "roscpp" "rospy")
set(test_diagnostic_aggregator_RUN_DEPENDS_diagnostic_aggregator_VERSION_GTE "1.8.9")
set(test_diagnostic_aggregator_TEST_DEPENDS )
set(test_diagnostic_aggregator_DOC_DEPENDS )
set(test_diagnostic_aggregator_URL_WEBSITE "http://ros.org/wiki/test_diagnostic_aggregator")
set(test_diagnostic_aggregator_URL_BUGTRACKER "")
set(test_diagnostic_aggregator_URL_REPOSITORY "")
set(test_diagnostic_aggregator_DEPRECATED "")