#!/usr/bin/env python

import rospy
import nav_msgs
import geometry_msgs


def convert():
	rospy.init_node("convert", anonymous=True)
	rospy.Subscriber("gps", gps, callback, queue_size = 1)
	rospy.spin()

if __name__=='__main__':
	convert()

def callback(data):
	z =1