# CMake generated Testfile for 
# Source directory: /home/pi/test/src/diagnostics/diagnostic_common_diagnostics
# Build directory: /home/pi/test/build_isolated/diagnostic_common_diagnostics
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_diagnostic_common_diagnostics_rostest_test_launch_test_cpu_monitor.launch "/home/pi/test/build_isolated/diagnostic_common_diagnostics/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/pi/test/src/catkin/cmake/test/run_tests.py" "/home/pi/test/build_isolated/diagnostic_common_diagnostics/test_results/diagnostic_common_diagnostics/rostest-test_launch_test_cpu_monitor.xml" "--return-code" "/home/pi/test/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/pi/test/src/diagnostics/diagnostic_common_diagnostics --package=diagnostic_common_diagnostics --results-filename test_launch_test_cpu_monitor.xml --results-base-dir \"/home/pi/test/build_isolated/diagnostic_common_diagnostics/test_results\" /home/pi/test/src/diagnostics/diagnostic_common_diagnostics/test/launch/test_cpu_monitor.launch ")
add_test(_ctest_diagnostic_common_diagnostics_rostest_test_launch_test_cpu_monitor_level_ok.launch "/home/pi/test/build_isolated/diagnostic_common_diagnostics/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/pi/test/src/catkin/cmake/test/run_tests.py" "/home/pi/test/build_isolated/diagnostic_common_diagnostics/test_results/diagnostic_common_diagnostics/rostest-test_launch_test_cpu_monitor_level_ok.xml" "--return-code" "/home/pi/test/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/pi/test/src/diagnostics/diagnostic_common_diagnostics --package=diagnostic_common_diagnostics --results-filename test_launch_test_cpu_monitor_level_ok.xml --results-base-dir \"/home/pi/test/build_isolated/diagnostic_common_diagnostics/test_results\" /home/pi/test/src/diagnostics/diagnostic_common_diagnostics/test/launch/test_cpu_monitor_level_ok.launch ")
add_test(_ctest_diagnostic_common_diagnostics_rostest_test_launch_test_cpu_monitor_level_warn.launch "/home/pi/test/build_isolated/diagnostic_common_diagnostics/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/pi/test/src/catkin/cmake/test/run_tests.py" "/home/pi/test/build_isolated/diagnostic_common_diagnostics/test_results/diagnostic_common_diagnostics/rostest-test_launch_test_cpu_monitor_level_warn.xml" "--return-code" "/home/pi/test/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/pi/test/src/diagnostics/diagnostic_common_diagnostics --package=diagnostic_common_diagnostics --results-filename test_launch_test_cpu_monitor_level_warn.xml --results-base-dir \"/home/pi/test/build_isolated/diagnostic_common_diagnostics/test_results\" /home/pi/test/src/diagnostics/diagnostic_common_diagnostics/test/launch/test_cpu_monitor_level_warn.launch ")
subdirs("gtest")
