set(_CATKIN_CURRENT_PACKAGE "kdl_msgs")
set(kdl_msgs_VERSION "0.0.0")
set(kdl_msgs_MAINTAINER "Johannes Meyer <johannes@intermodalics.eu>")
set(kdl_msgs_PACKAGE_FORMAT "2")
set(kdl_msgs_BUILD_DEPENDS "message_generation" "orocos_kdl" "std_msgs")
set(kdl_msgs_BUILD_EXPORT_DEPENDS "orocos_kdl" "std_msgs")
set(kdl_msgs_BUILDTOOL_DEPENDS "catkin")
set(kdl_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(kdl_msgs_EXEC_DEPENDS "message_runtime" "orocos_kdl" "std_msgs")
set(kdl_msgs_RUN_DEPENDS "message_runtime" "orocos_kdl" "std_msgs")
set(kdl_msgs_TEST_DEPENDS "roscpp_serialization" "roscpp_traits")
set(kdl_msgs_DOC_DEPENDS )
set(kdl_msgs_URL_WEBSITE "http://wiki.ros.org/kdl_msgs")
set(kdl_msgs_URL_BUGTRACKER "")
set(kdl_msgs_URL_REPOSITORY "")
set(kdl_msgs_DEPRECATED "")