set(kdl_msgs_SETUP_PY_VERSION "0.0.0")
set(kdl_msgs_SETUP_PY_SCRIPTS "")
set(kdl_msgs_SETUP_PY_PACKAGES "kdl_msgs")
set(kdl_msgs_SETUP_PY_PACKAGE_DIRS "src/kdl_msgs")
set(kdl_msgs_SETUP_PY_MODULES "")
set(kdl_msgs_SETUP_PY_MODULE_DIRS "")