// Generated by gencpp from file kdl_msgs/JntArrayStamped.msg
// DO NOT EDIT!


#ifndef KDL_MSGS_MESSAGE_JNTARRAYSTAMPED_H
#define KDL_MSGS_MESSAGE_JNTARRAYSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <kdl_msgs/JntArray.h>

namespace kdl_msgs
{
template <class ContainerAllocator>
struct JntArrayStamped_
{
  typedef JntArrayStamped_<ContainerAllocator> Type;

  JntArrayStamped_()
    : header()
    , joints()  {
    }
  JntArrayStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , joints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::kdl_msgs::JntArray_<ContainerAllocator>  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> const> ConstPtr;

}; // struct JntArrayStamped_

typedef ::kdl_msgs::JntArrayStamped_<std::allocator<void> > JntArrayStamped;

typedef boost::shared_ptr< ::kdl_msgs::JntArrayStamped > JntArrayStampedPtr;
typedef boost::shared_ptr< ::kdl_msgs::JntArrayStamped const> JntArrayStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kdl_msgs::JntArrayStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kdl_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/home/pi/test/src/std_msgs/msg'], 'kdl_msgs': ['/home/pi/test/src/kdl_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc6436c1eca974e807d4ae33aab49725";
  }

  static const char* value(const ::kdl_msgs::JntArrayStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc6436c1eca974e8ULL;
  static const uint64_t static_value2 = 0x07d4ae33aab49725ULL;
};

template<class ContainerAllocator>
struct DataType< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kdl_msgs/JntArrayStamped";
  }

  static const char* value(const ::kdl_msgs::JntArrayStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represents a stamped KDL::JntArray instance.\n\
\n\
Header header\n\
JntArray joints\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: kdl_msgs/JntArray\n\
# Represents a KDL::JntArray instance.\n\
\n\
float64[] data\n\
";
  }

  static const char* value(const ::kdl_msgs::JntArrayStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JntArrayStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kdl_msgs::JntArrayStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kdl_msgs::JntArrayStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joints: ";
    s << std::endl;
    Printer< ::kdl_msgs::JntArray_<ContainerAllocator> >::stream(s, indent + "  ", v.joints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KDL_MSGS_MESSAGE_JNTARRAYSTAMPED_H
