set(_CATKIN_CURRENT_PACKAGE "bondpy")
set(bondpy_VERSION "1.8.4")
set(bondpy_MAINTAINER "Michael Carroll <michael@openrobotics.org>")
set(bondpy_PACKAGE_FORMAT "3")
set(bondpy_BUILD_DEPENDS "bond" "rospy" "smclib")
set(bondpy_BUILD_EXPORT_DEPENDS )
set(bondpy_BUILDTOOL_DEPENDS "catkin" "python-setuptools" "python3-setuptools")
set(bondpy_BUILDTOOL_EXPORT_DEPENDS )
set(bondpy_EXEC_DEPENDS "rospy" "smclib" "uuid")
set(bondpy_RUN_DEPENDS "rospy" "smclib" "uuid")
set(bondpy_TEST_DEPENDS )
set(bondpy_DOC_DEPENDS )
set(bondpy_URL_WEBSITE "http://www.ros.org/wiki/bondpy")
set(bondpy_URL_BUGTRACKER "https://github.com/ros/bond_core/issues")
set(bondpy_URL_REPOSITORY "https://github.com/ros/bond_core")
set(bondpy_DEPRECATED "")