// Generated by gencpp from file pt_actions/NavigateAction.msg
// DO NOT EDIT!


#ifndef PT_ACTIONS_MESSAGE_NAVIGATEACTION_H
#define PT_ACTIONS_MESSAGE_NAVIGATEACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pt_actions/NavigateActionGoal.h>
#include <pt_actions/NavigateActionResult.h>
#include <pt_actions/NavigateActionFeedback.h>

namespace pt_actions
{
template <class ContainerAllocator>
struct NavigateAction_
{
  typedef NavigateAction_<ContainerAllocator> Type;

  NavigateAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  NavigateAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::pt_actions::NavigateActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::pt_actions::NavigateActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::pt_actions::NavigateActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::pt_actions::NavigateAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pt_actions::NavigateAction_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateAction_

typedef ::pt_actions::NavigateAction_<std::allocator<void> > NavigateAction;

typedef boost::shared_ptr< ::pt_actions::NavigateAction > NavigateActionPtr;
typedef boost::shared_ptr< ::pt_actions::NavigateAction const> NavigateActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pt_actions::NavigateAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pt_actions::NavigateAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pt_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'pt_actions': ['/home/ubuntu/catkin_ws/devel/share/pt_actions/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pt_actions::NavigateAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pt_actions::NavigateAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pt_actions::NavigateAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pt_actions::NavigateAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pt_actions::NavigateAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pt_actions::NavigateAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pt_actions::NavigateAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b214cf313cfaa350f3c95ed08187ee0";
  }

  static const char* value(const ::pt_actions::NavigateAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b214cf313cfaa35ULL;
  static const uint64_t static_value2 = 0x0f3c95ed08187ee0ULL;
};

template<class ContainerAllocator>
struct DataType< ::pt_actions::NavigateAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pt_actions/NavigateAction";
  }

  static const char* value(const ::pt_actions::NavigateAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pt_actions::NavigateAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
NavigateActionGoal action_goal\n\
NavigateActionResult action_result\n\
NavigateActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: pt_actions/NavigateActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
NavigateGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: pt_actions/NavigateGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the Goal\n\
#The latitudes and longitudes of the points to travel to.\n\
#Starting location is at index 0, First point\n\
#to travel to is at index 1 \n\
float64[] lats\n\
float64[] lons \n\
#The number of loops to do around the points\n\
uint8 loops \n\
\n\
#The square size for auto generating points\n\
float64 auto_size\n\
\n\
#The lookahead distance for the\n\
#Pure Pursuit Controller. higher values\n\
#cause the rover to converge to path more\n\
#slowly\n\
float64 lookahead_distance\n\
float64 max_angular_speed\n\
float64 threshold\n\
#The desired speed to drive along\n\
#the path\n\
float64 desired_speed\n\
\n\
#The start point index in the path\n\
uint8 start_point\n\
\n\
================================================================================\n\
MSG: pt_actions/NavigateActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
NavigateResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: pt_actions/NavigateResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
#The ending latitude and longitude on completion\n\
float64 end_lat\n\
float64 end_lon\n\
#The average(in metres) of how close the rover made it to the points\n\
float64 end_distance\n\
\n\
\n\
================================================================================\n\
MSG: pt_actions/NavigateActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
NavigateFeedback feedback\n\
\n\
================================================================================\n\
MSG: pt_actions/NavigateFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
#The current position of the rover\n\
float64 latitude\n\
float64 longitude\n\
\n\
#The total distance travelled\n\
float64 distanceTravelled\n\
\n\
#The current point on the path we are tracking from\n\
uint8 curPoint\n\
\n\
#The current status of the tracker. If 0, tracker is waiting for RTK lock\n\
#If 1, tracker has an RTK lock and is actively tracking path\n\
uint8 status\n\
\n\
";
  }

  static const char* value(const ::pt_actions::NavigateAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pt_actions::NavigateAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pt_actions::NavigateAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pt_actions::NavigateAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::pt_actions::NavigateActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::pt_actions::NavigateActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::pt_actions::NavigateActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PT_ACTIONS_MESSAGE_NAVIGATEACTION_H
