#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/pi/ros_catkin_ws/devel_isolated/roslaunch:/home/pi/ros_catkin_ws/devel_isolated/roscpp_serialization:/home/pi/ros_catkin_ws/devel_isolated/rostime:/home/pi/ros_catkin_ws/devel_isolated/rosservice:/home/pi/ros_catkin_ws/devel_isolated/rospy:/home/pi/ros_catkin_ws/devel_isolated/rosparam:/home/pi/ros_catkin_ws/devel_isolated/roslib:/home/pi/ros_catkin_ws/devel_isolated/rospack:/home/pi/ros_catkin_ws/devel_isolated/rosmaster:/home/pi/ros_catkin_ws/devel_isolated/rosmake:/home/pi/ros_catkin_ws/devel_isolated/roslisp:/home/pi/ros_catkin_ws/devel_isolated/roslang:/home/pi/ros_catkin_ws/devel_isolated/rosgraph:/home/pi/ros_catkin_ws/devel_isolated/roscreate:/home/pi/ros_catkin_ws/devel_isolated/roscpp_traits:/home/pi/ros_catkin_ws/devel_isolated/rosclean:/home/pi/ros_catkin_ws/devel_isolated/rosbuild:/home/pi/ros_catkin_ws/devel_isolated/rosboost_cfg:/home/pi/ros_catkin_ws/devel_isolated/rosbash:/home/pi/ros_catkin_ws/devel_isolated/ros_environment:/home/pi/ros_catkin_ws/devel_isolated/ros_comm:/home/pi/ros_catkin_ws/devel_isolated/ros:/home/pi/ros_catkin_ws/devel_isolated/opencv_tests:/home/pi/ros_catkin_ws/devel_isolated/mk:/home/pi/ros_catkin_ws/devel_isolated/message_runtime:/home/pi/ros_catkin_ws/devel_isolated/message_generation:/home/pi/ros_catkin_ws/devel_isolated/image_common:/home/pi/ros_catkin_ws/devel_isolated/cpp_common:/home/pi/ros_catkin_ws/devel_isolated/class_loader:/home/pi/ros_catkin_ws/devel_isolated/cmake_modules:/home/pi/ros_catkin_ws/devel_isolated/genpy:/home/pi/ros_catkin_ws/devel_isolated/gennodejs:/home/pi/ros_catkin_ws/devel_isolated/genlisp:/home/pi/ros_catkin_ws/devel_isolated/geneus:/home/pi/ros_catkin_ws/devel_isolated/gencpp:/home/pi/ros_catkin_ws/devel_isolated/genmsg:/home/pi/ros_catkin_ws/devel_isolated/catkin:/home/pi/rosbots_catkin_ws/devel:/home/pi/ros_catkin_ws/build/opt/ros/kinetic:/home/pi/ros_catkin_ws/devel_isolated/orocos_kdl"
export LD_LIBRARY_PATH="/home/pi/ros_catkin_ws/devel_isolated/roslaunch/lib:/home/pi/ros_catkin_ws/devel_isolated/roscpp_serialization/lib:/home/pi/ros_catkin_ws/devel_isolated/rostime/lib:/home/pi/ros_catkin_ws/devel_isolated/rosservice/lib:/home/pi/ros_catkin_ws/devel_isolated/rospy/lib:/home/pi/ros_catkin_ws/devel_isolated/rosparam/lib:/home/pi/ros_catkin_ws/devel_isolated/roslib/lib:/home/pi/ros_catkin_ws/devel_isolated/rospack/lib:/home/pi/ros_catkin_ws/devel_isolated/rosmaster/lib:/home/pi/ros_catkin_ws/devel_isolated/rosmake/lib:/home/pi/ros_catkin_ws/devel_isolated/roslisp/lib:/home/pi/ros_catkin_ws/devel_isolated/roslang/lib:/home/pi/ros_catkin_ws/devel_isolated/rosgraph/lib:/home/pi/ros_catkin_ws/devel_isolated/roscreate/lib:/home/pi/ros_catkin_ws/devel_isolated/roscpp_traits/lib:/home/pi/ros_catkin_ws/devel_isolated/rosclean/lib:/home/pi/ros_catkin_ws/devel_isolated/rosbuild/lib:/home/pi/ros_catkin_ws/devel_isolated/rosboost_cfg/lib:/home/pi/ros_catkin_ws/devel_isolated/rosbash/lib:/home/pi/ros_catkin_ws/devel_isolated/ros_environment/lib:/home/pi/ros_catkin_ws/devel_isolated/opencv_tests/lib:/home/pi/ros_catkin_ws/devel_isolated/mk/lib:/home/pi/ros_catkin_ws/devel_isolated/message_runtime/lib:/home/pi/ros_catkin_ws/devel_isolated/message_generation/lib:/home/pi/ros_catkin_ws/devel_isolated/cpp_common/lib:/home/pi/ros_catkin_ws/devel_isolated/class_loader/lib:/home/pi/ros_catkin_ws/devel_isolated/cmake_modules/lib:/home/pi/ros_catkin_ws/devel_isolated/genpy/lib:/home/pi/ros_catkin_ws/devel_isolated/gennodejs/lib:/home/pi/ros_catkin_ws/devel_isolated/genlisp/lib:/home/pi/ros_catkin_ws/devel_isolated/geneus/lib:/home/pi/ros_catkin_ws/devel_isolated/gencpp/lib:/home/pi/ros_catkin_ws/devel_isolated/genmsg/lib:/home/pi/ros_catkin_ws/devel_isolated/catkin/lib:/home/pi/rosbots_catkin_ws/devel/lib:/home/pi/ros_catkin_ws/build/opt/ros/kinetic/lib:/home/pi/ros_catkin_ws/devel_isolated/orocos_kdl/lib"
export PATH="/home/pi/ros_catkin_ws/devel_isolated/roslaunch/bin:$PATH"
export PKG_CONFIG_PATH="/home/pi/ros_catkin_ws/devel_isolated/roslaunch/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/roscpp_serialization/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/rostime/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/rosservice/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/rospy/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/rosparam/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/roslib/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/rospack/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/rosmaster/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/rosmake/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/roslisp/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/roslang/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/rosgraph/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/roscreate/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/roscpp_traits/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/rosclean/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/rosbuild/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/rosboost_cfg/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/rosbash/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/ros_environment/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/opencv_tests/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/mk/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/message_runtime/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/message_generation/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/cpp_common/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/class_loader/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/cmake_modules/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/genpy/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/gennodejs/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/genlisp/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/geneus/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/gencpp/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/genmsg/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/catkin/lib/pkgconfig:/home/pi/ros_catkin_ws/build/opt/ros/kinetic/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/orocos_kdl/lib/pkgconfig"
export PYTHONPATH="/home/pi/ros_catkin_ws/devel_isolated/roslaunch/lib/python2.7/dist-packages:$PYTHONPATH"
export ROSLISP_PACKAGE_DIRECTORIES="/home/pi/ros_catkin_ws/devel_isolated/roslaunch/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/pi/ros_catkin_ws/src/ros_comm/roslaunch:$ROS_PACKAGE_PATH"