; Auto-generated. Do not edit!


(cl:in-package tedusar_nav_msgs-msg)


;//! \htmlinclude ExecutePathFeedback.msg.html

(cl:defclass <ExecutePathFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:integer
    :initform 0))
)

(cl:defclass ExecutePathFeedback (<ExecutePathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecutePathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecutePathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tedusar_nav_msgs-msg:<ExecutePathFeedback> is deprecated: use tedusar_nav_msgs-msg:ExecutePathFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <ExecutePathFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tedusar_nav_msgs-msg:feedback-val is deprecated.  Use tedusar_nav_msgs-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecutePathFeedback>) ostream)
  "Serializes a message object of type '<ExecutePathFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'feedback)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'feedback)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'feedback)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'feedback)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecutePathFeedback>) istream)
  "Deserializes a message object of type '<ExecutePathFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'feedback)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'feedback)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'feedback)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'feedback)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecutePathFeedback>)))
  "Returns string type for a message object of type '<ExecutePathFeedback>"
  "tedusar_nav_msgs/ExecutePathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecutePathFeedback)))
  "Returns string type for a message object of type 'ExecutePathFeedback"
  "tedusar_nav_msgs/ExecutePathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecutePathFeedback>)))
  "Returns md5sum for a message object of type '<ExecutePathFeedback>"
  "cbfbf3355c876d056ca78e89534a5173")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecutePathFeedback)))
  "Returns md5sum for a message object of type 'ExecutePathFeedback"
  "cbfbf3355c876d056ca78e89534a5173")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecutePathFeedback>)))
  "Returns full string definition for message of type '<ExecutePathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%uint32 feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecutePathFeedback)))
  "Returns full string definition for message of type 'ExecutePathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%uint32 feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecutePathFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecutePathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecutePathFeedback
    (cl:cons ':feedback (feedback msg))
))
