; Auto-generated. Do not edit!


(cl:in-package tedusar_nav_msgs-msg)


;//! \htmlinclude ExecutePathResult.msg.html

(cl:defclass <ExecutePathResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass ExecutePathResult (<ExecutePathResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecutePathResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecutePathResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tedusar_nav_msgs-msg:<ExecutePathResult> is deprecated: use tedusar_nav_msgs-msg:ExecutePathResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <ExecutePathResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tedusar_nav_msgs-msg:result-val is deprecated.  Use tedusar_nav_msgs-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecutePathResult>) ostream)
  "Serializes a message object of type '<ExecutePathResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'result)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'result)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'result)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecutePathResult>) istream)
  "Deserializes a message object of type '<ExecutePathResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'result)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'result)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'result)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecutePathResult>)))
  "Returns string type for a message object of type '<ExecutePathResult>"
  "tedusar_nav_msgs/ExecutePathResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecutePathResult)))
  "Returns string type for a message object of type 'ExecutePathResult"
  "tedusar_nav_msgs/ExecutePathResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecutePathResult>)))
  "Returns md5sum for a message object of type '<ExecutePathResult>"
  "13d5d28ceaaadbc975dd072a2e10b88a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecutePathResult)))
  "Returns md5sum for a message object of type 'ExecutePathResult"
  "13d5d28ceaaadbc975dd072a2e10b88a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecutePathResult>)))
  "Returns full string definition for message of type '<ExecutePathResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecutePathResult)))
  "Returns full string definition for message of type 'ExecutePathResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecutePathResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecutePathResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecutePathResult
    (cl:cons ':result (result msg))
))
