set(_CATKIN_CURRENT_PACKAGE "rosdiagnostic")
set(rosdiagnostic_VERSION "1.9.3")
set(rosdiagnostic_MAINTAINER "Guillaume Autran <gautran@clearpath.ai>")
set(rosdiagnostic_PACKAGE_FORMAT "2")
set(rosdiagnostic_BUILD_DEPENDS )
set(rosdiagnostic_BUILD_EXPORT_DEPENDS )
set(rosdiagnostic_BUILDTOOL_DEPENDS "catkin")
set(rosdiagnostic_BUILDTOOL_EXPORT_DEPENDS )
set(rosdiagnostic_EXEC_DEPENDS "rospy" "diagnostic_msgs")
set(rosdiagnostic_RUN_DEPENDS "rospy" "diagnostic_msgs")
set(rosdiagnostic_TEST_DEPENDS )
set(rosdiagnostic_DOC_DEPENDS )
set(rosdiagnostic_URL_WEBSITE "")
set(rosdiagnostic_URL_BUGTRACKER "")
set(rosdiagnostic_URL_REPOSITORY "")
set(rosdiagnostic_DEPRECATED "")