#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/pi/test/devel_isolated/rosdiagnostic:/home/pi/test/devel_isolated/roscreate:/home/pi/test/devel_isolated/rosclean:/home/pi/test/devel_isolated/rosbuild:/home/pi/test/devel_isolated/rosboost_cfg:/home/pi/test/devel_isolated/rosbash:/home/pi/test/devel_isolated/ros_control:/home/pi/test/devel_isolated/ros_comm:/home/pi/test/devel_isolated/ros:/home/pi/test/devel_isolated/nodelet_core:/home/pi/test/devel_isolated/mk:/home/pi/test/devel_isolated/geometry2:/home/pi/test/devel_isolated/geometry:/home/pi/test/devel_isolated/gazebo_ros_pkgs:/home/pi/test/devel_isolated/gazebo_dev:/home/pi/test/devel_isolated/diff_sim:/home/pi/test/devel_isolated/diagnostics:/home/pi/test/devel_isolated/common_msgs:/home/pi/test/devel_isolated/bond_core:/home/pi/test/devel_isolated/actionlib_tools:/home/pi/test/devel_isolated/genpy:/home/pi/test/devel_isolated/gencpp:/home/pi/test/devel_isolated/catkin:/home/pi/rosbots_catkin_ws/devel:/home/pi/ros_catkin_ws/build/opt/ros/kinetic:/home/pi/test/devel_isolated/orocos_kdl"
export LD_LIBRARY_PATH="/home/pi/test/devel_isolated/roscreate/lib:/home/pi/test/devel_isolated/rosclean/lib:/home/pi/test/devel_isolated/rosbuild/lib:/home/pi/test/devel_isolated/rosboost_cfg/lib:/home/pi/test/devel_isolated/rosbash/lib:/home/pi/test/devel_isolated/mk/lib:/home/pi/test/devel_isolated/gazebo_dev/lib:/home/pi/test/devel_isolated/diff_sim/lib:/home/pi/test/devel_isolated/actionlib_tools/lib:/home/pi/test/devel_isolated/genpy/lib:/home/pi/test/devel_isolated/gencpp/lib:/home/pi/test/devel_isolated/catkin/lib:/home/pi/rosbots_catkin_ws/devel/lib:/home/pi/ros_catkin_ws/build/opt/ros/kinetic/lib:/home/pi/test/devel_isolated/orocos_kdl/lib"
export PKG_CONFIG_PATH="/home/pi/test/devel_isolated/roscreate/lib/pkgconfig:/home/pi/test/devel_isolated/rosclean/lib/pkgconfig:/home/pi/test/devel_isolated/rosbuild/lib/pkgconfig:/home/pi/test/devel_isolated/rosboost_cfg/lib/pkgconfig:/home/pi/test/devel_isolated/rosbash/lib/pkgconfig:/home/pi/test/devel_isolated/mk/lib/pkgconfig:/home/pi/test/devel_isolated/gazebo_dev/lib/pkgconfig:/home/pi/test/devel_isolated/diff_sim/lib/pkgconfig:/home/pi/test/devel_isolated/actionlib_tools/lib/pkgconfig:/home/pi/test/devel_isolated/genpy/lib/pkgconfig:/home/pi/test/devel_isolated/gencpp/lib/pkgconfig:/home/pi/test/devel_isolated/catkin/lib/pkgconfig:/home/pi/ros_catkin_ws/build/opt/ros/kinetic/lib/pkgconfig:/home/pi/test/devel_isolated/orocos_kdl/lib/pkgconfig"
export ROSLISP_PACKAGE_DIRECTORIES="/home/pi/test/devel_isolated/rosdiagnostic/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/pi/test/src/diagnostics/rosdiagnostic:$ROS_PACKAGE_PATH"