#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/pi/ros_catkin_ws/devel_isolated/rosbash:/home/pi/ros_catkin_ws/devel_isolated/ros_environment:/home/pi/ros_catkin_ws/devel_isolated/ros_comm:/home/pi/ros_catkin_ws/devel_isolated/ros:/home/pi/ros_catkin_ws/devel_isolated/opencv_tests:/home/pi/ros_catkin_ws/devel_isolated/mk:/home/pi/ros_catkin_ws/devel_isolated/message_runtime:/home/pi/ros_catkin_ws/devel_isolated/message_generation:/home/pi/ros_catkin_ws/devel_isolated/image_common:/home/pi/ros_catkin_ws/devel_isolated/cpp_common:/home/pi/ros_catkin_ws/devel_isolated/class_loader:/home/pi/ros_catkin_ws/devel_isolated/cmake_modules:/home/pi/ros_catkin_ws/devel_isolated/genpy:/home/pi/ros_catkin_ws/devel_isolated/gennodejs:/home/pi/ros_catkin_ws/devel_isolated/genlisp:/home/pi/ros_catkin_ws/devel_isolated/geneus:/home/pi/ros_catkin_ws/devel_isolated/gencpp:/home/pi/ros_catkin_ws/devel_isolated/genmsg:/home/pi/ros_catkin_ws/devel_isolated/catkin:/home/pi/rosbots_catkin_ws/devel:/home/pi/ros_catkin_ws/build/opt/ros/kinetic:/home/pi/ros_catkin_ws/devel_isolated/orocos_kdl"
export LD_LIBRARY_PATH="/home/pi/ros_catkin_ws/devel_isolated/rosbash/lib:/home/pi/ros_catkin_ws/devel_isolated/ros_environment/lib:/home/pi/ros_catkin_ws/devel_isolated/opencv_tests/lib:/home/pi/ros_catkin_ws/devel_isolated/mk/lib:/home/pi/ros_catkin_ws/devel_isolated/message_runtime/lib:/home/pi/ros_catkin_ws/devel_isolated/message_generation/lib:/home/pi/ros_catkin_ws/devel_isolated/cpp_common/lib:/home/pi/ros_catkin_ws/devel_isolated/class_loader/lib:/home/pi/ros_catkin_ws/devel_isolated/cmake_modules/lib:/home/pi/ros_catkin_ws/devel_isolated/genpy/lib:/home/pi/ros_catkin_ws/devel_isolated/gennodejs/lib:/home/pi/ros_catkin_ws/devel_isolated/genlisp/lib:/home/pi/ros_catkin_ws/devel_isolated/geneus/lib:/home/pi/ros_catkin_ws/devel_isolated/gencpp/lib:/home/pi/ros_catkin_ws/devel_isolated/genmsg/lib:/home/pi/ros_catkin_ws/devel_isolated/catkin/lib:/home/pi/rosbots_catkin_ws/devel/lib:/home/pi/ros_catkin_ws/build/opt/ros/kinetic/lib:/home/pi/ros_catkin_ws/devel_isolated/orocos_kdl/lib"
export PATH="/home/pi/ros_catkin_ws/devel_isolated/rosbash/bin:$PATH"
export PKG_CONFIG_PATH="/home/pi/ros_catkin_ws/devel_isolated/rosbash/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/ros_environment/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/opencv_tests/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/mk/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/message_runtime/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/message_generation/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/cpp_common/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/class_loader/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/cmake_modules/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/genpy/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/gennodejs/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/genlisp/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/geneus/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/gencpp/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/genmsg/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/catkin/lib/pkgconfig:/home/pi/ros_catkin_ws/build/opt/ros/kinetic/lib/pkgconfig:/home/pi/ros_catkin_ws/devel_isolated/orocos_kdl/lib/pkgconfig"
export ROSLISP_PACKAGE_DIRECTORIES="/home/pi/ros_catkin_ws/devel_isolated/rosbash/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/pi/ros_catkin_ws/src/ros/rosbash:$ROS_PACKAGE_PATH"