set(_CATKIN_CURRENT_PACKAGE "urdf")
set(urdf_VERSION "1.12.12")
set(urdf_MAINTAINER "Chris Lalancette <clalancette@osrfoundation.org>, Shane Loretz <sloretz@osrfoundation.org>")
set(urdf_PACKAGE_FORMAT "2")
set(urdf_BUILD_DEPENDS "liburdfdom-dev" "liburdfdom-headers-dev" "rosconsole_bridge" "roscpp" "urdf_parser_plugin" "pluginlib" "cmake_modules" "tinyxml")
set(urdf_BUILD_DEPENDS_pluginlib_VERSION_GTE "1.11.2")
set(urdf_BUILD_EXPORT_DEPENDS "tinyxml" "liburdfdom-headers-dev")
set(urdf_BUILDTOOL_DEPENDS "catkin")
set(urdf_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(urdf_BUILDTOOL_EXPORT_DEPENDS )
set(urdf_EXEC_DEPENDS "liburdfdom-dev" "rosconsole_bridge" "roscpp" "pluginlib" "tinyxml")
set(urdf_EXEC_DEPENDS_pluginlib_VERSION_GTE "1.11.2")
set(urdf_RUN_DEPENDS "liburdfdom-dev" "rosconsole_bridge" "roscpp" "pluginlib" "tinyxml" "liburdfdom-headers-dev")
set(urdf_RUN_DEPENDS_pluginlib_VERSION_GTE "1.11.2")
set(urdf_TEST_DEPENDS "rostest")
set(urdf_DOC_DEPENDS )
set(urdf_URL_WEBSITE "http://ros.org/wiki/urdf")
set(urdf_URL_BUGTRACKER "https://github.com/ros/urdf/issues")
set(urdf_URL_REPOSITORY "https://github.com/ros/urdf")
set(urdf_DEPRECATED "")