# CMake generated Testfile for 
# Source directory: /home/pi/test/src/ros_control/joint_limits_interface
# Build directory: /home/pi/test/build_isolated/joint_limits_interface
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_joint_limits_interface_gtest_joint_limits_interface_test "/home/pi/test/build_isolated/joint_limits_interface/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/pi/test/src/catkin/cmake/test/run_tests.py" "/home/pi/test/build_isolated/joint_limits_interface/test_results/joint_limits_interface/gtest-joint_limits_interface_test.xml" "--return-code" "/home/pi/test/devel_isolated/joint_limits_interface/lib/joint_limits_interface/joint_limits_interface_test --gtest_output=xml:/home/pi/test/build_isolated/joint_limits_interface/test_results/joint_limits_interface/gtest-joint_limits_interface_test.xml")
add_test(_ctest_joint_limits_interface_gtest_joint_limits_urdf_test "/home/pi/test/build_isolated/joint_limits_interface/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/pi/test/src/catkin/cmake/test/run_tests.py" "/home/pi/test/build_isolated/joint_limits_interface/test_results/joint_limits_interface/gtest-joint_limits_urdf_test.xml" "--return-code" "/home/pi/test/devel_isolated/joint_limits_interface/lib/joint_limits_interface/joint_limits_urdf_test --gtest_output=xml:/home/pi/test/build_isolated/joint_limits_interface/test_results/joint_limits_interface/gtest-joint_limits_urdf_test.xml")
add_test(_ctest_joint_limits_interface_rostest_test_joint_limits_rosparam.test "/home/pi/test/build_isolated/joint_limits_interface/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/pi/test/src/catkin/cmake/test/run_tests.py" "/home/pi/test/build_isolated/joint_limits_interface/test_results/joint_limits_interface/rostest-test_joint_limits_rosparam.xml" "--return-code" "/home/pi/test/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/pi/test/src/ros_control/joint_limits_interface --package=joint_limits_interface --results-filename test_joint_limits_rosparam.xml --results-base-dir \"/home/pi/test/build_isolated/joint_limits_interface/test_results\" /home/pi/test/src/ros_control/joint_limits_interface/test/joint_limits_rosparam.test ")
subdirs("gtest")
