// Auto-generated. Do not edit!

// (in-package pt_actions.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class NavigateFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.latitude = null;
      this.longitude = null;
      this.distanceTravelled = null;
      this.curPoint = null;
      this.status = null;
    }
    else {
      if (initObj.hasOwnProperty('latitude')) {
        this.latitude = initObj.latitude
      }
      else {
        this.latitude = 0.0;
      }
      if (initObj.hasOwnProperty('longitude')) {
        this.longitude = initObj.longitude
      }
      else {
        this.longitude = 0.0;
      }
      if (initObj.hasOwnProperty('distanceTravelled')) {
        this.distanceTravelled = initObj.distanceTravelled
      }
      else {
        this.distanceTravelled = 0.0;
      }
      if (initObj.hasOwnProperty('curPoint')) {
        this.curPoint = initObj.curPoint
      }
      else {
        this.curPoint = 0;
      }
      if (initObj.hasOwnProperty('status')) {
        this.status = initObj.status
      }
      else {
        this.status = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type NavigateFeedback
    // Serialize message field [latitude]
    bufferOffset = _serializer.float64(obj.latitude, buffer, bufferOffset);
    // Serialize message field [longitude]
    bufferOffset = _serializer.float64(obj.longitude, buffer, bufferOffset);
    // Serialize message field [distanceTravelled]
    bufferOffset = _serializer.float64(obj.distanceTravelled, buffer, bufferOffset);
    // Serialize message field [curPoint]
    bufferOffset = _serializer.uint8(obj.curPoint, buffer, bufferOffset);
    // Serialize message field [status]
    bufferOffset = _serializer.uint8(obj.status, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type NavigateFeedback
    let len;
    let data = new NavigateFeedback(null);
    // Deserialize message field [latitude]
    data.latitude = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [longitude]
    data.longitude = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [distanceTravelled]
    data.distanceTravelled = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [curPoint]
    data.curPoint = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [status]
    data.status = _deserializer.uint8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 26;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pt_actions/NavigateFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '472ed5bc364b6797971771f5605285cb';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    #The current position of the rover
    float64 latitude
    float64 longitude
    
    #The total distance travelled
    float64 distanceTravelled
    
    #The current point on the path we are tracking from
    uint8 curPoint
    
    #The current status of the tracker. If 0, tracker is waiting for RTK lock
    #If 1, tracker has an RTK lock and is actively tracking path
    uint8 status
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new NavigateFeedback(null);
    if (msg.latitude !== undefined) {
      resolved.latitude = msg.latitude;
    }
    else {
      resolved.latitude = 0.0
    }

    if (msg.longitude !== undefined) {
      resolved.longitude = msg.longitude;
    }
    else {
      resolved.longitude = 0.0
    }

    if (msg.distanceTravelled !== undefined) {
      resolved.distanceTravelled = msg.distanceTravelled;
    }
    else {
      resolved.distanceTravelled = 0.0
    }

    if (msg.curPoint !== undefined) {
      resolved.curPoint = msg.curPoint;
    }
    else {
      resolved.curPoint = 0
    }

    if (msg.status !== undefined) {
      resolved.status = msg.status;
    }
    else {
      resolved.status = 0
    }

    return resolved;
    }
};

module.exports = NavigateFeedback;
