# CMake generated Testfile for 
# Source directory: /home/pi/test/src/bond_core/test_bond
# Build directory: /home/pi/test/build_isolated/test_bond
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_test_bond_rostest_test_test_cpp.launch "/home/pi/test/build_isolated/test_bond/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/pi/test/src/catkin/cmake/test/run_tests.py" "/home/pi/test/build_isolated/test_bond/test_results/test_bond/rostest-test_test_cpp.xml" "--return-code" "/home/pi/test/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/pi/test/src/bond_core/test_bond --package=test_bond --results-filename test_test_cpp.xml --results-base-dir \"/home/pi/test/build_isolated/test_bond/test_results\" /home/pi/test/src/bond_core/test_bond/test/test_cpp.launch ")
add_test(_ctest_test_bond_rostest_test_test_python.launch "/home/pi/test/build_isolated/test_bond/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/pi/test/src/catkin/cmake/test/run_tests.py" "/home/pi/test/build_isolated/test_bond/test_results/test_bond/rostest-test_test_python.xml" "--return-code" "/home/pi/test/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/pi/test/src/bond_core/test_bond --package=test_bond --results-filename test_test_python.xml --results-base-dir \"/home/pi/test/build_isolated/test_bond/test_results\" /home/pi/test/src/bond_core/test_bond/test/test_python.launch ")
add_test(_ctest_test_bond_rostest_test_test_callbacks_cpp.launch "/home/pi/test/build_isolated/test_bond/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/pi/test/src/catkin/cmake/test/run_tests.py" "/home/pi/test/build_isolated/test_bond/test_results/test_bond/rostest-test_test_callbacks_cpp.xml" "--return-code" "/home/pi/test/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/pi/test/src/bond_core/test_bond --package=test_bond --results-filename test_test_callbacks_cpp.xml --results-base-dir \"/home/pi/test/build_isolated/test_bond/test_results\" /home/pi/test/src/bond_core/test_bond/test/test_callbacks_cpp.launch ")
add_test(_ctest_test_bond_rostest_test_test_callbacks_py.launch "/home/pi/test/build_isolated/test_bond/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/pi/test/src/catkin/cmake/test/run_tests.py" "/home/pi/test/build_isolated/test_bond/test_results/test_bond/rostest-test_test_callbacks_py.xml" "--return-code" "/home/pi/test/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/pi/test/src/bond_core/test_bond --package=test_bond --results-filename test_test_callbacks_py.xml --results-base-dir \"/home/pi/test/build_isolated/test_bond/test_results\" /home/pi/test/src/bond_core/test_bond/test/test_callbacks_py.launch ")
subdirs("gtest")
